# Generated by Django 3.0.5 on 2020-04-26 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200427_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='date_published',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 4, 27, 0, 34, 17, 207302)),
        ),
    ]
